### ISSUE TITLE
Add support for transpiler: none

### ISSUE THREAD

**Issue by dsebastien** [rolaveric/karma-systemjs#61]
I'm trying to add karma-systemjs to my project, but apparently it tries to require the configured transpiler. In my case I don't use any transpiler with SystemJS, thus I have transpiler: "none".

Here's the error I get from karma-systemjs:

```
[WARNING] Looking up paths with require.resolve() is deprecated.
Please add "none" to your SystemJS config paths.
Cannot find "none".
  Did you forget to install it ?
  npm install none --save-dev
```

**Comment by rolaveric** [comment]
It should work if you set `transpiler: null`

**Comment by dsebastien** [comment]
Thanks, this should indeed work. Although I'm not sure it's the cleanest solution.
The JSPM CLI explicitly checks on "none" in some places (eg https://github.com/jspm/jspm-cli/blob/eea1b6fc76feff771fa56c6decf390a981e6c7c3/lib/core.js#L165)

**Comment by rolaveric** [comment]
No problem - I'll add `"none"` to the switch statement.

**Comment by rolaveric** [comment]
Fixed by b635b90fe54d21e80b78f07b4d4363886d956f84

**Comment by dsebastien** [comment]
Great, thanks!
I'll try it out in a minute

**Comment by dsebastien** [comment]
I think I'm a bit further, but I still get some errors with the new release:

```
13 12 2015 17:41:20.976:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
13 12 2015 17:41:20.980:INFO [launcher]: Starting browser PhantomJS
13 12 2015 17:41:21.592:INFO [PhantomJS 1.9.8 (Windows 8 0.0.0)]: Connected on socket JbitWjvhIG8GFrUAAAAA with id 29564952
13 12 2015 17:41:21.674:WARN [web-server]: 404: /base/none.js
PhantomJS 1.9.8 (Windows 8 0.0.0) ERROR
  Error: XHR error (404 Not Found) loading c:/dev/wks/midnightLightV2/none.js
        Error loading c:/dev/wks/midnightLightV2/none.js
        Error loading c:/dev/wks/midnightLightV2/.tmp/test/injector.spec.js

PhantomJS 1.9.8 (Windows 8 0.0.0): Executed 0 of 0 ERROR (0.09 secs / 0 secs)
```

I'm not sure where the problem lies.. :(

**Comment by rolaveric** [comment]
Well that "/base/none.js" call is definitely a bug, though benign.  I'll get that fixed.

The XHR errors are coming from the browser, so it's actually trying to retrieve from the file system rather that through the web server that Karma starts.
Maybe try testing in Chrome or Firefox and use the Developer Tools to work out what's going on.

**Comment by dsebastien** [comment]
I'm looking into how /base/none.js is being requested in the browser. It ain't very straightforward, but apparently this is the test file that causes this error:

```
/*
import {
  it,
  describe,
  expect,
  inject
} from 'angular2/testing';
import {
  APP_ID
} from 'angular2/angular2';


describe('default test injector', () => {
  it('should provide default id', inject([APP_ID], (id) => {
    expect(id).toBe('a');
  }));
});
*/
console.log("cool");

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInRlc3QvaW5qZWN0b3Iuc3BlYy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7RUFpQkU7QUFDRixPQUFPLENBQUMsR0FBRyxDQUFDLE1BQU0sQ0FBQyxDQUFDIiwiZmlsZSI6InRlc3QvaW5qZWN0b3Iuc3BlYy5qcyIsInNvdXJjZVJvb3QiOiIvIn0=
```

Apparently SystemJS doesn't care about the comments and notices the import statements, thinking it is ES2015+ code and thus trying to transpile it, somehow forgetting that I don't want transpilation :).

I might be wrong but this seems to be somehow right as removing that test file fixes my issue.

**Comment by rolaveric** [comment]
As a workaround, you should be able to use a `meta` property in your SystemJS config to specify the import style.

**Comment by dsebastien** [comment]
As a workaround I've just removed the commented out es2015 code :)
